name: Preprocessing Pipeline

on:
  push:
    paths:
      - 'preprocessing/automate_Ahmad_Raihan.py'
      - 'dataset_raw/**'
      - '.github/workflows/main.yml'

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
    - name: Run actions/checkout@v3
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Check Env
      run: |
        echo "Python version: $(python --version)"
        echo "Current directory: $(pwd)"
        ls -la

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Ahmad_Raihan.py

    - name: Upload processed datasets
      uses: actions/upload-artifact@v4
      with:
        name: processed-datasets
        path: preprocessing/diamond_preprocessing/*.csv